package ViewerApp;


/**
* ViewerApp/Viewer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from View.idl
* samedi 2 avril 2016 01 h 30 CEST
*/

public interface Viewer extends ViewerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Viewer
