package ViewerApp;


/**
* ViewerApp/ViewerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from View.idl
* samedi 2 avril 2016 01 h 30 CEST
*/

abstract public class ViewerHelper
{
  private static String  _id = "IDL:ViewerApp/Viewer:1.0";

  public static void insert (org.omg.CORBA.Any a, ViewerApp.Viewer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ViewerApp.Viewer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ViewerApp.ViewerHelper.id (), "Viewer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ViewerApp.Viewer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ViewerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ViewerApp.Viewer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ViewerApp.Viewer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ViewerApp.Viewer)
      return (ViewerApp.Viewer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ViewerApp._ViewerStub stub = new ViewerApp._ViewerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ViewerApp.Viewer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ViewerApp.Viewer)
      return (ViewerApp.Viewer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ViewerApp._ViewerStub stub = new ViewerApp._ViewerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
