package ViewerApp;

/**
* ViewerApp/ViewerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from View.idl
* samedi 2 avril 2016 01 h 30 CEST
*/

public final class ViewerHolder implements org.omg.CORBA.portable.Streamable
{
  public ViewerApp.Viewer value = null;

  public ViewerHolder ()
  {
  }

  public ViewerHolder (ViewerApp.Viewer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ViewerApp.ViewerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ViewerApp.ViewerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ViewerApp.ViewerHelper.type ();
  }

}
