package ViewerApp;


/**
* ViewerApp/ViewerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from View.idl
* samedi 2 avril 2016 01 h 30 CEST
*/

public interface ViewerOperations 
{
  byte[] view ();
  void mouseMove (int x, int y);
  void mouseClick ();
  void mousePress ();
  void mouseRelease ();
  void mouseRightClick ();
  void mouseRightPress ();
  void mouseRightRelease ();
  void keyPress (int code);
  void keyClick (int code);
  void keyRelease (int code);
  void shutdown ();
} // interface ViewerOperations
