package ViewerApp.ViewerPackage;


/**
* ViewerApp/ViewerPackage/byteArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from View.idl
* samedi 2 avril 2016 01 h 30 CEST
*/

public final class byteArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public byteArrayHolder ()
  {
  }

  public byteArrayHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ViewerApp.ViewerPackage.byteArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ViewerApp.ViewerPackage.byteArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ViewerApp.ViewerPackage.byteArrayHelper.type ();
  }

}
